# ansible/collect.yml — v1.6.0 (final)
# Fetch newest metrics_*.tar.gz from remote to a configurable repo-root path

- name: Collect latest metrics archive to controller
  hosts: bench
  gather_facts: no
  vars:
    repo_path: /opt/ic-benches
    archive_glob: "{{ repo_path }}/.bench_archives/metrics_*.tar.gz"
    # override with: METRICS_DIR=/abs/path make collect-local
    metrics_dir: "{{ lookup('env','METRICS_DIR') | default((playbook_dir + '/../metrics'), true) | realpath }}"

  tasks:
    - name: Show metrics_dir (controller)
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "metrics_dir resolved to: {{ metrics_dir }}"

    - name: Find newest metrics archive on remote
      ansible.builtin.shell: "ls -1t {{ archive_glob }} 2>/dev/null | head -n1"
      register: newest
      changed_when: false
      failed_when: newest.stdout | trim == ""

    - name: Ensure metrics_dir exists (controller)
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ metrics_dir }}"
        state: directory
        mode: "0755"

    - name: Fetch newest archive (remote → controller)
      ansible.builtin.fetch:
        src: "{{ newest.stdout | trim }}"
        dest: "{{ metrics_dir }}/"
        flat: yes

    - name: Report fetched path
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "✅ Fetched: {{ metrics_dir }}/{{ (newest.stdout | trim) | basename }}"
